packages:
  - '.'
  - 'website'

peerDependencyRules:
  ignoreMissing:
    - vite
    - react
    - react-dom
    - '@types/react'
    - '@types/react-dom'
  allowedVersions:
    vite: 8.0.0
    react: 19.2.4
    react-dom: 19.2.4
    '@types/react': 19.2.14
    '@types/react-dom': 19.2.3
engineStrict: false
allowBuilds:
  esbuild: true
  lefthook: true
  '@swc/core': false
